# Generated by Django 3.2.4 on 2021-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CorrectChoice',
        ),
    ]
