# Generated by Django 3.2.4 on 2021-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210608_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questions', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrectAnswer1',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrectAnswer2',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrectAnswer3',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
